version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build and test:
    executor: node/default
    docker:
      - image: cypress/base:16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm 
      - run:
          command: npm install
          name: install dependencies 
      - run:
          command: npx cypress open
          name: run cypress tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  test_my_app:
    jobs:
      - build and test
