version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm 
      - run:
          command: npm install
          name: install dependencies 
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
